# Production profile configuration
spring:
  # Database configuration for production
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  # JPA/Hibernate configuration for production
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  
  # Flyway configuration for production
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Logging configuration for production
logging:
  level:
    root: INFO
    com.suscompanion: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: WARN

# Server configuration for production
server:
  tomcat:
    max-threads: 200
    min-spare-threads: 20
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048

# Security settings for production
jwt:
  secret: ${JWT_SECRET}